# Site settings
title: La Terminal de Macale # site title
description: >- # site description
  Plataforma Educatica Informática
lang: es-ES # default lang
timezone: Europe/Madrid # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/piharpi/jekyll-klise # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: ">_ La Terminal de Macale" # author name
  subtitle: "Alejandro Herrera Jiménez"
  bio: >- # tell to the world
    Profesional en Administración de Sistemas Informáticos con experiencia en la gestión de infraestructuras tecnológicas y servicios. Durante mi formación como Técnico Superior en Administración de Sistemas Informáticos en Red en el IES Gonzalo Nazareno de Dos Hermanas (Sevilla), he desarrollado habilidades en la administración de sistemas operativos GNU/Linux (Debian, Ubuntu, RHEL, CentOS...) y Windows Server, así como en redes (VLAN, NAT, OSPF, IPv6, VPN) y seguridad (Iptables, Nftables, OpenSSL, GPG, OpenVPN, WireGuard). Cuento con experiencia en bases de datos SQL y NoSQL, virtualización y entornos cloud (Proxmox, KVM, LXC, OpenStack), metodologías DevOps (Docker, Kubernetes, Jenkins, GitHub Actions) y en Infraestructura como Código mediante Ansible y Vagrant. Además, he gestionado servidores web (Apache y Nginx), proxys inversos, balanceadores de carga (HAProxy), servidores DNS (BIND9) y servicios de correo electrónico (Postfix, Dovecot, SpamAssassin).
  username:
  github: Alehache97 # github username
  twitter: # twitter username
  facebook: 
  email: alejandrohjasir@gmail.com # email adress
  avatar: /assets/img/inicio.gif # change with your own avatar

# URL settings
url: "https://klise.now.sh" #
baseurl: ""
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
